#!/bin/bash

# From: http://plankenau.com/blog/post/gaussian-blur-lock-screen-i3lock/

sleep 0.5

screenshot=/tmp/screenshot.png

scrot $screenshot
convert $screenshot -blur 0x5 $screenshot
i3lock -i $screenshot
