#!/bin/sh

if [ $# -eq 0 ] ; then
    echo "Please specify a port number."
    exit 1
fi

info=$(netstat -tlnp 2>&1 | awk "/:$1/ {print \$NF}")
pid=$(echo $info | cut -d '/' -f 1)
processname=$(echo $info | cut -d '/' -f 2)

if [ -z "$info" ]; then
    echo "No process found."
    exit 1
fi

kill -9 $pid
echo "Process '$processname' killed."
