#!/bin/sh

# From http://stackoverflow.com/a/32744703/604041
echocolor() {
  COLOR='\033[1;33m'
  NC='\033[0m'
  printf "${COLOR}$1${NC}\n"
}

notify-send "Starting a system update..."

echocolor "Entering ~/dotfiles/..."
cd /home/dinduks/dotfiles/
echocolor "Stashing..."
git stash -u
echocolor "Pulling every submodule..."
git submodule foreach git pull
echocolor "Adding the updated submodules to the staging area..."
git add .
echocolor "Commiting..."
git commit -m "[Vim] Update all the plugins"
echocolor "Pushing..."
git push
echocolor "Poping the stash..."
git stash pop

notify-send "Done updating dotfiles."

echocolor "\nEntering ~/.oh-my-zsh/..."
cd /home/dinduks/.oh-my-zsh/
echocolor "Reseting the state..."
git checkout .
echocolor "Pulling new changes..."
git pull

notify-send "Done updating oh-my-zsh."

echocolor "Updating i3-gaps..."
git clone --branch gaps https://github.com/Airblader/i3.git /tmp/i3
cd /tmp/i3
make -j 4
sudo make install
i3-msg restart
notify-send "Done updating i3-gaps. Finished."

echocolor "\nDone."
